import type { APIRoute } from 'astro';

const SITE_URL = 'https://danielgierach.com';

const pages = [
  // Core pages, highest priority
  { path: '/',          changefreq: 'weekly',  priority: '1.0' },
  { path: '/listings',        changefreq: 'daily',   priority: '0.95' },
  { path: '/walkthrough',     changefreq: 'monthly', priority: '0.90' },
  { path: '/property-worth',  changefreq: 'monthly', priority: '0.88' },
  { path: '/property-report', changefreq: 'monthly', priority: '0.9' },
  { path: '/results',          changefreq: 'monthly', priority: '0.85' },
  { path: '/about',               changefreq: 'monthly', priority: '0.8' },
  { path: '/reviews',             changefreq: 'monthly', priority: '0.8' },
  { path: '/brisbane-inner-east', changefreq: 'monthly', priority: '0.9' },
  { path: '/suburbs/seven-hills',    changefreq: 'weekly',  priority: '0.92' },
  { path: '/suburbs/carina',         changefreq: 'weekly',  priority: '0.92' },
  { path: '/suburbs/morningside',    changefreq: 'weekly',  priority: '0.92' },
  { path: '/suburbs/cannon-hill',    changefreq: 'weekly',  priority: '0.92' },
  { path: '/suburbs/carina-heights', changefreq: 'monthly', priority: '0.85' },
  { path: '/suburbs/east-brisbane',  changefreq: 'monthly', priority: '0.85' },
  { path: '/suburbs/coorparoo',      changefreq: 'monthly', priority: '0.85' },
  { path: '/suburbs/tingalpa',       changefreq: 'monthly', priority: '0.85' },
  { path: '/suburbs/murarrie',       changefreq: 'weekly',  priority: '0.92' },
  { path: '/suburbs/brisbane-cbd',        changefreq: 'monthly', priority: '0.85' },
  { path: '/suburbs/fortitude-valley',    changefreq: 'monthly', priority: '0.85' },
  { path: '/suburbs/new-farm',            changefreq: 'monthly', priority: '0.85' },
  { path: '/suburbs/teneriffe',           changefreq: 'monthly', priority: '0.85' },
  { path: '/suburbs/kangaroo-point',      changefreq: 'monthly', priority: '0.85' },
  { path: '/suburbs/woolloongabba',       changefreq: 'monthly', priority: '0.85' },
  { path: '/suburbs/bulimba',             changefreq: 'monthly', priority: '0.85' },
  { path: '/suburbs/hawthorne',           changefreq: 'monthly', priority: '0.85' },
  { path: '/suburbs/balmoral',            changefreq: 'monthly', priority: '0.85' },
  { path: '/suburbs/norman-park',         changefreq: 'weekly',  priority: '0.92' },
  { path: '/suburbs/camp-hill',           changefreq: 'monthly', priority: '0.85' },
  { path: '/suburbs/hemmant',             changefreq: 'monthly', priority: '0.85' },
  { path: '/suburbs/carindale',           changefreq: 'monthly', priority: '0.85' },
  { path: '/suburbs/belmont',             changefreq: 'monthly', priority: '0.85' },
  { path: '/suburbs/greenslopes',         changefreq: 'monthly', priority: '0.85' },
  { path: '/suburbs/holland-park',        changefreq: 'monthly', priority: '0.85' },
  { path: '/suburbs/holland-park-west',   changefreq: 'monthly', priority: '0.85' },
  { path: '/suburbs/mount-gravatt',       changefreq: 'monthly', priority: '0.85' },
  { path: '/suburbs/mount-gravatt-east',  changefreq: 'monthly', priority: '0.85' },
  { path: '/suburbs/upper-mount-gravatt', changefreq: 'monthly', priority: '0.85' },
  { path: '/suburbs/tarragindi',          changefreq: 'monthly', priority: '0.85' },
  { path: '/suburbs/annerley',           changefreq: 'monthly', priority: '0.85' },
  { path: '/suburbs/ascot',              changefreq: 'monthly', priority: '0.85' },
  { path: '/suburbs/dutton-park',        changefreq: 'monthly', priority: '0.85' },
  { path: '/suburbs/hamilton',           changefreq: 'monthly', priority: '0.85' },
  { path: '/suburbs/paddington',         changefreq: 'monthly', priority: '0.85' },
  { path: '/suburbs/red-hill',           changefreq: 'monthly', priority: '0.85' },
  { path: '/suburbs/stones-corner',      changefreq: 'monthly', priority: '0.85' },
  { path: '/suburbs/west-end',           changefreq: 'monthly', priority: '0.85' },
  { path: '/contact',             changefreq: 'monthly', priority: '0.8' },

  // Tools index + individual tools (long-tail keyword traffic)
  { path: '/tools',                       changefreq: 'monthly', priority: '0.8' },
  { path: '/tools/valuation',             changefreq: 'monthly', priority: '0.75' },
  { path: '/tools/mortgage',              changefreq: 'monthly', priority: '0.75' },
  { path: '/tools/stamp-duty',            changefreq: 'monthly', priority: '0.75' },
  { path: '/tools/selling-costs',         changefreq: 'monthly', priority: '0.75' },
  { path: '/tools/borrowing-power',       changefreq: 'monthly', priority: '0.75' },
  { path: '/tools/investment-yield',      changefreq: 'monthly', priority: '0.75' },
  { path: '/tools/dcf',                  changefreq: 'monthly', priority: '0.75' },
  { path: '/tools/equity-calculator',     changefreq: 'monthly', priority: '0.75' },
  { path: '/tools/negative-gearing',      changefreq: 'monthly', priority: '0.75' },
  { path: '/tools/rent-vs-buy',           changefreq: 'monthly', priority: '0.75' },
  { path: '/tools/portfolio-builder',     changefreq: 'monthly', priority: '0.75' },
  { path: '/tools/smsf-calculator',       changefreq: 'monthly', priority: '0.75' },
  { path: '/tools/school-catchment',     changefreq: 'monthly', priority: '0.8' },
  { path: '/tools/zoning-map',           changefreq: 'monthly', priority: '0.8' },
  { path: '/tools/renovation-roi',        changefreq: 'monthly', priority: '0.7' },
  { path: '/tools/suburb-match',          changefreq: 'monthly', priority: '0.7' },
  { path: '/tools/property-compare',      changefreq: 'monthly', priority: '0.7' },
  { path: '/tools/heatmap',              changefreq: 'weekly',  priority: '0.75' },
  { path: '/tools/flood-risk',           changefreq: 'monthly', priority: '0.7' },
  { path: '/tools/brisbane-2032',        changefreq: 'monthly', priority: '0.65' },
  { path: '/tools/capital-gains',        changefreq: 'monthly', priority: '0.65' },
  { path: '/tools/commute-cost',         changefreq: 'monthly', priority: '0.65' },
  { path: '/tools/deposit-savings',      changefreq: 'monthly', priority: '0.65' },
  { path: '/tools/depreciation-estimator', changefreq: 'monthly', priority: '0.65' },
  { path: '/tools/first-home-buyer',     changefreq: 'monthly', priority: '0.65' },
  { path: '/tools/granny-flat-roi',      changefreq: 'monthly', priority: '0.65' },
  { path: '/tools/land-tax',             changefreq: 'monthly', priority: '0.65' },
  { path: '/tools/lmi-calculator',       changefreq: 'monthly', priority: '0.65' },
  { path: '/tools/local-eats',           changefreq: 'monthly', priority: '0.65' },
  { path: '/tools/open-home-checklist',  changefreq: 'monthly', priority: '0.65' },
  { path: '/tools/presale-checklist',    changefreq: 'monthly', priority: '0.65' },
  { path: '/tools/rate-sensitivity',     changefreq: 'monthly', priority: '0.65' },
  // New seller-decision tools (April 2026)
  { path: '/tools/appraisal-reality-check',    changefreq: 'monthly', priority: '0.85' },
  { path: '/tools/method-of-sale',             changefreq: 'monthly', priority: '0.85' },
  { path: '/tools/buyer-profile',              changefreq: 'monthly', priority: '0.85' },
  { path: '/tools/agent-conditioning-checker', changefreq: 'monthly', priority: '0.8'  },
  { path: '/tools/net-proceeds-deep-dive',     changefreq: 'monthly', priority: '0.8'  },
  { path: '/tools/holding-costs',              changefreq: 'monthly', priority: '0.8'  },
  { path: '/tools/price-reduction-decision',   changefreq: 'monthly', priority: '0.8'  },
  { path: '/tools/multiple-offers',            changefreq: 'monthly', priority: '0.8'  },
  { path: '/tools/whole-of-move',              changefreq: 'monthly', priority: '0.8'  },
  { path: '/tools/bridging-relocation-finance',changefreq: 'monthly', priority: '0.75' },
  { path: '/tools/rent-vs-sell',               changefreq: 'monthly', priority: '0.8'  },
  { path: '/tools/tenanted-vs-vacant',         changefreq: 'monthly', priority: '0.75' },
  { path: '/tools/auction-reserve',            changefreq: 'monthly', priority: '0.75' },
  { path: '/tools/auction-bid-tracker',        changefreq: 'monthly', priority: '0.7'  },
  { path: '/tools/defect-triage',              changefreq: 'monthly', priority: '0.8'  },
  { path: '/tools/off-market-decision',        changefreq: 'monthly', priority: '0.8'  },
  { path: '/tools/campaign-benchmark',         changefreq: 'monthly', priority: '0.75' },
  { path: '/tools/cgt-timing',                 changefreq: 'monthly', priority: '0.75' },
  { path: '/tools/settlement-date',            changefreq: 'monthly', priority: '0.7'  },
  { path: '/tools/body-corp-disclosure',       changefreq: 'monthly', priority: '0.75' },
  // Building / architecture / planning education articles (April 2026)
  { path: '/insights/types-of-residential-property-australia',          changefreq: 'monthly', priority: '0.7' },
  { path: '/insights/brisbane-house-styles-architectural-periods',      changefreq: 'monthly', priority: '0.7' },
  { path: '/insights/house-anatomy-eaves-soffits-slabs-fascia',         changefreq: 'monthly', priority: '0.7' },
  { path: '/insights/building-materials-brisbane-homes',                changefreq: 'monthly', priority: '0.7' },
  { path: '/insights/slab-design-types-brisbane',                       changefreq: 'monthly', priority: '0.7' },
  { path: '/insights/cladding-facade-types-brisbane',                   changefreq: 'monthly', priority: '0.7' },
  { path: '/insights/building-professionals-architect-designer-draftsperson-engineer', changefreq: 'monthly', priority: '0.7' },
  { path: '/insights/build-process-with-architect-step-by-step',        changefreq: 'monthly', priority: '0.7' },
  { path: '/insights/queensland-brisbane-zoning-explained',             changefreq: 'monthly', priority: '0.75' },
  { path: '/insights/types-of-build-project-custom-modular-prefab',     changefreq: 'monthly', priority: '0.7' },
  { path: '/insights/first-home-buyer-help-history-and-current-options', changefreq: 'monthly', priority: '0.85' },

  // Insights index + articles (content marketing / organic search)
  { path: '/insights',                              changefreq: 'weekly',  priority: '0.8' },

  // Selling-in suburb guides, high commercial intent
  // Priority suburbs first (0.82), remaining suburbs (0.78)
  { path: '/insights/selling-in-morningside',       changefreq: 'monthly', priority: '0.82' },
  { path: '/insights/selling-in-murarrie',          changefreq: 'monthly', priority: '0.82' },
  { path: '/insights/selling-in-cannon-hill',       changefreq: 'monthly', priority: '0.82' },
  { path: '/insights/selling-in-seven-hills',       changefreq: 'monthly', priority: '0.82' },
  { path: '/insights/selling-in-norman-park',       changefreq: 'monthly', priority: '0.82' },
  { path: '/insights/selling-in-carina',            changefreq: 'monthly', priority: '0.82' },
  { path: '/insights/selling-in-camp-hill',         changefreq: 'monthly', priority: '0.82' },
  { path: '/insights/selling-in-hawthorne',         changefreq: 'monthly', priority: '0.82' },
  { path: '/insights/selling-in-bulimba',           changefreq: 'monthly', priority: '0.82' },
  { path: '/insights/selling-in-balmoral',          changefreq: 'monthly', priority: '0.78' },
  { path: '/insights/selling-in-annerley',          changefreq: 'monthly', priority: '0.78' },
  { path: '/insights/selling-in-ascot',             changefreq: 'monthly', priority: '0.78' },
  { path: '/insights/selling-in-belmont',           changefreq: 'monthly', priority: '0.78' },
  { path: '/insights/selling-in-brisbane-cbd',      changefreq: 'monthly', priority: '0.78' },
  { path: '/insights/selling-in-carina-heights',    changefreq: 'monthly', priority: '0.78' },
  { path: '/insights/selling-in-carindale',         changefreq: 'monthly', priority: '0.78' },
  { path: '/insights/selling-in-coorparoo',         changefreq: 'monthly', priority: '0.78' },
  { path: '/insights/selling-in-dutton-park',       changefreq: 'monthly', priority: '0.78' },
  { path: '/insights/selling-in-east-brisbane',     changefreq: 'monthly', priority: '0.78' },
  { path: '/insights/selling-in-fortitude-valley',  changefreq: 'monthly', priority: '0.78' },
  { path: '/insights/selling-in-greenslopes',       changefreq: 'monthly', priority: '0.78' },
  { path: '/insights/selling-in-hamilton',          changefreq: 'monthly', priority: '0.78' },
  { path: '/insights/selling-in-hemmant',           changefreq: 'monthly', priority: '0.78' },
  { path: '/insights/selling-in-holland-park',      changefreq: 'monthly', priority: '0.78' },
  { path: '/insights/selling-in-holland-park-west', changefreq: 'monthly', priority: '0.78' },
  { path: '/insights/selling-in-kangaroo-point',    changefreq: 'monthly', priority: '0.78' },
  { path: '/insights/selling-in-mount-gravatt',     changefreq: 'monthly', priority: '0.78' },
  { path: '/insights/selling-in-mount-gravatt-east',changefreq: 'monthly', priority: '0.78' },
  { path: '/insights/selling-in-new-farm',          changefreq: 'monthly', priority: '0.78' },
  { path: '/insights/selling-in-paddington',        changefreq: 'monthly', priority: '0.78' },
  { path: '/insights/selling-in-red-hill',          changefreq: 'monthly', priority: '0.78' },
  { path: '/insights/selling-in-stones-corner',     changefreq: 'monthly', priority: '0.78' },
  { path: '/insights/selling-in-tarragindi',        changefreq: 'monthly', priority: '0.78' },
  { path: '/insights/selling-in-teneriffe',         changefreq: 'monthly', priority: '0.78' },
  { path: '/insights/selling-in-tingalpa',          changefreq: 'monthly', priority: '0.78' },
  { path: '/insights/selling-in-upper-mount-gravatt',changefreq: 'monthly', priority: '0.78' },
  { path: '/insights/selling-in-west-end',          changefreq: 'monthly', priority: '0.78' },
  { path: '/insights/selling-in-woolloongabba',     changefreq: 'monthly', priority: '0.78' },

  // High-priority seller intent articles (0.75)
  { path: '/insights/best-time-to-sell-brisbane',               changefreq: 'monthly', priority: '0.75' },
  { path: '/insights/cost-of-selling-house-brisbane',           changefreq: 'monthly', priority: '0.75' },
  { path: '/insights/how-long-does-it-take-to-sell-a-home-in-brisbane', changefreq: 'monthly', priority: '0.75' },
  { path: '/insights/how-much-is-my-home-worth-brisbane',       changefreq: 'monthly', priority: '0.75' },
  { path: '/insights/how-to-choose-a-real-estate-agent-brisbane', changefreq: 'monthly', priority: '0.75' },

  // General insights articles
  { path: '/insights/auction-strategy',             changefreq: 'monthly', priority: '0.7' },
  { path: '/insights/building-pest-report',         changefreq: 'monthly', priority: '0.7' },
  { path: '/insights/buyers-agent',                 changefreq: 'monthly', priority: '0.7' },
  { path: '/insights/engage-right-builder',         changefreq: 'monthly', priority: '0.65' },
  { path: '/insights/flood-mapping',                changefreq: 'monthly', priority: '0.65' },
  { path: '/insights/mortgage-broker',              changefreq: 'monthly', priority: '0.7' },
  { path: '/insights/prepare-home-for-sale',        changefreq: 'monthly', priority: '0.7' },
  { path: '/insights/stamp-duty-queensland',        changefreq: 'monthly', priority: '0.7' },
  { path: '/insights/unconditional-offer',          changefreq: 'monthly', priority: '0.65' },
  { path: '/insights/understanding-the-contract',   changefreq: 'monthly', priority: '0.65' },
  { path: '/insights/what-happens-at-settlement',   changefreq: 'monthly', priority: '0.65' },
  { path: '/insights/when-to-sell',                 changefreq: 'monthly', priority: '0.7' },
  { path: '/insights/airbnb-vs-longterm',           changefreq: 'monthly', priority: '0.7' },
  { path: '/insights/body-corporate',               changefreq: 'monthly', priority: '0.7' },
  { path: '/insights/brisbane-house-styles',        changefreq: 'monthly', priority: '0.7' },
  { path: '/insights/brisbane-inner-east-value',    changefreq: 'monthly', priority: '0.7' },
  { path: '/insights/buying-with-tenant',           changefreq: 'monthly', priority: '0.7' },
  { path: '/insights/heritage-overlays-brisbane',   changefreq: 'monthly', priority: '0.7' },
  { path: '/insights/prewar-homes-brisbane',        changefreq: 'monthly', priority: '0.7' },
  { path: '/insights/queenslander-vs-postwar',      changefreq: 'monthly', priority: '0.7' },
  { path: '/insights/solicitor-vs-conveyancer-qld', changefreq: 'monthly', priority: '0.7' },

  // Legal, low priority
  { path: '/privacy',    changefreq: 'yearly', priority: '0.2' },
  { path: '/terms',      changefreq: 'yearly', priority: '0.2' },
];

const today = new Date().toISOString().split('T')[0];

export const GET: APIRoute = () => {
  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${pages.map(p => `  <url>
    <loc>${SITE_URL}${p.path}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${p.changefreq}</changefreq>
    <priority>${p.priority}</priority>
  </url>`).join('\n')}
</urlset>`;

  return new Response(xml, {
    headers: {
      'Content-Type': 'application/xml',
      'Cache-Control': 'public, max-age=86400',
    },
  });
};
