#!/bin/zsh
# Nightly quarterly-report runner (launchd: com.danielgierach.quarterly-reports).
# Builds every suburb PDF waiting in the dashboard (status 'uploaded'), then
# commits and pushes the generated data so Vercel publishes it. No AI in the
# loop; uploading a PDF on /app/quarterly-reports is the whole trigger.
set -euo pipefail
export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
REPO="$HOME/DanielGierachProperty"
LOG="$HOME/Library/Logs/quarterly-reports.log"
LOCK="/tmp/quarterly-nightly.lock"

exec >> "$LOG" 2>&1
echo "── $(date '+%Y-%m-%d %H:%M') nightly run"

if [ -e "$LOCK" ]; then echo "lock present, skipping"; exit 0; fi
touch "$LOCK"
trap 'rm -f "$LOCK"' EXIT

cd "$REPO"
node scripts/build-quarterly-report.mjs --all

if git diff --quiet && git diff --cached --quiet && [ -z "$(git status --porcelain src/data/reports public/img/reports)" ]; then
  echo "no changes"
  exit 0
fi

# Validate before pushing: a broken JSON must not take the site down.
npm run build

git add src/data/reports public/img/reports
git commit -m "Quarterly reports: nightly automatic build

Generated by scripts/quarterly-nightly.sh from the dashboard's uploaded
Pricefinder PDFs."
git push dang281 main
echo "pushed"
