#!/bin/zsh
# Nightly quarterly-report runner (launchd: com.danielgierach.quarterly-reports).
# Builds every suburb PDF waiting in the dashboard (status 'uploaded'), then
# commits and pushes the generated data so Vercel publishes it. No AI in the
# loop; uploading a PDF on /app/quarterly-reports is the whole trigger.
set -euo pipefail
# node/npm are installed via nvm, whose bin dir is NOT in launchd's minimal
# PATH. Without this the job failed nightly with "command not found: node"
# (exit 127). Prepend the newest installed nvm node bin so node/npm resolve.
NVM_NODE_BIN="$(ls -td "$HOME"/.nvm/versions/node/*/bin 2>/dev/null | head -1 || true)"
export PATH="${NVM_NODE_BIN:+$NVM_NODE_BIN:}/opt/homebrew/bin:/usr/local/bin:$PATH"
REPO="$HOME/DanielGierachProperty"
LOG="$HOME/Library/Logs/quarterly-reports.log"
LOCK="/tmp/quarterly-nightly.lock"

exec >> "$LOG" 2>&1
echo "── $(date '+%Y-%m-%d %H:%M') nightly run"

if [ -e "$LOCK" ]; then echo "lock present, skipping"; exit 0; fi
touch "$LOCK"
trap 'rm -f "$LOCK"' EXIT

cd "$REPO"
node scripts/build-quarterly-report.mjs --all
# OG cards are a nice-to-have; a Puppeteer hiccup must never block the
# commit/push of freshly built report data below. The script only renders
# cards that don't exist yet, so a failed night retries on the next run.
node scripts/generate-report-og.mjs || echo "og generation failed (non-fatal, retries next run)"

# Gate on exactly the paths committed below; unrelated dirty files elsewhere
# in the tree must neither trigger nor break a nightly publish.
if [ -z "$(git status --porcelain src/data/reports public/img/reports)" ]; then
  echo "no changes"
  exit 0
fi

# Validate before pushing: a broken JSON must not take the site down.
npm run build

git add src/data/reports public/img/reports
git commit -m "Quarterly reports: nightly automatic build

Generated by scripts/quarterly-nightly.sh from the dashboard's uploaded
Pricefinder PDFs."
git push dang281 main
echo "pushed"
